/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <string>
#include "../cpp/static_lib/math_add.h"
/* Header for class com_example_skia_application_MainActivity */

#ifndef _Included_com_example_skia_application_MainActivity
#define _Included_com_example_skia_application_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_skia_application_MainActivity
 * Method:    stringFromJNI
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_skia_1application_MainActivity_stringFromJNI
  (JNIEnv *env, jobject jobj, jstring str) {
    const char* c_name = env->GetStringUTFChars(str, NULL);

    std::string hello = "Hello from C++, ";
    std::string name(c_name);

    int res = MathAdd::add(1, 2);
    auto tt = hello + name + std::to_string(res);

    return env->NewStringUTF((tt).c_str());
}

#ifdef __cplusplus
}
#endif
#endif
